export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-gray-900 to-black"
      style={{
        color: "var(--foreground)"
        // , background: "var(--background)"
      }}>
        {children}
      </body>
    </html>
  )
}
